Change FirstBoot Cron install/remove to BASH

diff --git a/scripts/global/installFirstBoot b/scripts/global/installFirstBoot
--- a/scripts/global/installFirstBoot
+++ b/scripts/global/installFirstBoot
@@ -1,9 +1,18 @@
-#!/usr/bin/puppet apply
+#!/bin/bash
+echo -e "\n==Install FirstBoot Cron=="
+if [[ "x${dateformat}" != "x" ]]; then
+	echo -e "Begin at $(date +"${dateformat}")"
+fi
 
-cron { 'First Boot Startup':
-  ensure      => present,
-  environment => "PATH=${path}",
-  user        => 'root',
-  command     => 'doFirstBoot',
-  special     => 'reboot',
-}
+cat << EOF > /etc/cron.d/FirstBoot
+PATH=$PATH
+@reboot root doFirstBoot
+EOF
+exval=$?
+
+if [ $exval -eq 0 ]; then
+        echo -e "\t[DONE]"
+else
+        echo -e "\t[FAIL] Code: ${exval}"
+        exit $exval
+fi
diff --git a/scripts/global/removeFirstBoot b/scripts/global/removeFirstBoot
--- a/scripts/global/removeFirstBoot
+++ b/scripts/global/removeFirstBoot
@@ -1,6 +1,15 @@
-#!/usr/bin/puppet apply
+#!/bin/bash
+echo -e "\n==Remove FirstBoot Cron=="
+if [[ "x${dateformat}" != "x" ]]; then
+        echo -e "Begin at $(date +"${dateformat}")"
+fi
 
-cron { 'First Boot Startup':
-  ensure => absent,
-  user   => 'root',
-}
+rm /etc/cron.d/FirstBoot
+exval=$?
+
+if [ $exval -eq 0 ]; then
+        echo -e "\t[DONE]"
+else
+        echo -e "\t[FAIL] Code: ${exval}"
+        exit $exval
+fi
