Add logging into the scripts

diff --git a/scripts/global/installPythonPackages b/scripts/global/installPythonPackages
--- a/scripts/global/installPythonPackages
+++ b/scripts/global/installPythonPackages
@@ -1,7 +1,11 @@
 #!/bin/bash
+echo "==Python Package Installer=="
+if [[ "x${dateformat}" != "x" ]]; then
+	echo -e "Begin at $(date +"${dateformat}")"
+fi
 
 if [ $# -lt 1 ]; then
-	echo "Please specify at least one package to install" >&2
+	echo -e "\t[FAIL] Please specify at least one package to install" >&2
 	exit 1
 fi
 
@@ -10,9 +14,16 @@ if pip3 --version &>/dev/null; then
 elif pip --version &>/dev/null; then
 	pip=pip
 else
-	echo "No suitable pip found found" >&2
+	echo -e "\t[FAIL] No suitable pip found found" >&2
 	exit 2
 fi
 
-$pip install --upgrade "$@" #&>/dev/null
-exit $?
+echo -e "\tRunning $pip install..."
+$pip install --upgrade "$@" &>/dev/null
+exval=$?
+if [ $exval -eq 0 ]; then
+	echo -e "\t[DONE]"
+else
+	echo -e "\t[FAIL] Code: ${exval}"
+	exit $exval
+fi
diff --git a/scripts/global/installSystemPackages b/scripts/global/installSystemPackages
--- a/scripts/global/installSystemPackages
+++ b/scripts/global/installSystemPackages
@@ -1,17 +1,30 @@
 #!/bin/bash
+echo "==System Package Installer=="
+if [[ "x${dateformat}" != "x" ]]; then
+	echo -e "Begin at $(date +"${dateformat}")"
+fi
 
 if [ $# -lt 1 ]; then
-	echo "Please specify at least one package to install" >&2
+	echo -e "\t[FAIL] Please specify at least one package to install" >&2
 	exit 1
 fi
 
 if apt-get --version &>/dev/null; then
+	echo -e "\tRunning apt-get install..."
 	apt-get install --assume-yes "$@" &>/dev/null
-	exit $?
+	exval=$?
 elif yum --version &>/dev/null; then
+	echo -e "\tRunning yum install..."
 	yum --assumeyes install "$@" &>/dev/null
-	exit $?
+	exval=$?
 else
-	echo "No package mangers found" >&2
+	echo -e "\t[FAIL] No package mangers found" >&2
 	exit 2
+fi
+
+if [ $exval -eq 0 ]; then
+	echo -e "\t[DONE]"
+else
+	echo -e "\t[FAIL] Code: ${exval}"
+	exit $exval
 fi
diff --git a/scripts/global/upgradeSystemPackages b/scripts/global/upgradeSystemPackages
--- a/scripts/global/upgradeSystemPackages
+++ b/scripts/global/upgradeSystemPackages
@@ -1,16 +1,29 @@
 #!/bin/bash
+echo "==System Package Updater=="
+if [[ "x${dateformat}" != "x" ]]; then
+	echo -e "Begin at $(date +"${dateformat}")"
+fi
 
 if apt-get --version &>/dev/null; then
+	echo -e "Running apt-get update..."
 	apt-get update &>/dev/null
 	exval=$?
-	if [ $exval -ne 0 ]; then
-		exit $exval
+	if [ $exval -eq 0 ]; then
+		echo -e "Running apt-get upgrade..."
+		apt-get upgrade --assume-yes &>/dev/null
+		exval=$?
 	fi
-	apt-get upgrade --assume-yes &>/dev/null
-	exit $?
 fi
 
 if yum --version &>/dev/null; then
+	echo -e "Running yum upgrade..."
 	yum --assumeyes upgrade  &>/dev/null
-	exit $?
+	exval=$?
+fi
+
+if [ $exval -eq 0 ]; then
+	echo -e "\t[DONE]"
+else
+	echo -e "\t[FAIL] Code: ${exval}"
+	exit $exval
 fi
